= Seagull

Simple 2D OpenGL engine based in C++

Goal is to be simple and easy to use engine for simple simulations.

== How to Build

Before building, make sure to go into seagull/seagull/vendor/glew/auto and run
`make` here first, otherwise you will get an error when building seagull saying
that you are missing glew files.
You should also comment out line 1137 and 1135 of seagull/seagull/vendor/assimp/code/CMakeLists.txt
as a work around for some warnings that can occur when building that will cause
the build to stop.

=== Build on Visual Studio 2019

Before you begin, make sure that you have already downloaded the windows version
of cmake and it is on your $PATH. If you try and use the cmake that comes with WSL, you won't have the
option to generate a Visual Studio solution.

```
cd Build
cmake .. -G "Visual Studio 16 2019"
```

Open up generated visual studio solution.


=== Build on WSL2 (Mingw32)

Before you begin, make sure that you have already downloaded the windows version
of cmake and it is on your $PATH. If you try and use the cmake that comes with WSL, you won't have the
option to generate a Visual Studio solution.

```
cd Build
cmake .. -G "MinGW Makefiles"
mingw32-make
```



=== Build on Linux

```
brew install cmake
cd Build
cmake ..
make
```

=== Build on MacOS

Ensure xcode build tools are installed already (needed for make, g++, etc).
Use homebrew for installing `cmake`.

```
mkdir xcode
cd xcode
cmake -G Xcode ..
```

Open the resulting xcode project file.
